### ISSUE TITLE
Compilation error running lichess-bot.py cloned straight from GitHub, no modifications

### ISSUE THREAD

**Issue by stevehjohn** [lichess-bot-devs/lichess-bot#1049]
**Describe the bug**
I get the following error when executing `python3 lichess-bot.py`

```
Traceback (most recent call last):
  File "/Users/steve.john/Git/UsefulRepos/lichess-bot/lichess-bot.py", line 2, in <module>
    from lib.lichess_bot import start_program
  File "/Users/steve.john/Git/UsefulRepos/lichess-bot/lib/lichess_bot.py", line 3, in <module>
    import chess
ModuleNotFoundError: No module named 'chess'
```

**To Reproduce**
1. Clone the repo.
2. Enter the repo folder and type `python3 lichess-bot.py;

**Expected behavior**
Not get this error.

**Logs**
None

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version: 3.13.0
 - Terminal: iTerm2

**Additional context**
No other context.

**Comment by stevehjohn** [comment]
Oope. Should have read the instructions about requirements. Soz.
