### ISSUE TITLE
After reconnection during a game, lichess-bot sends UCI search command with 0 time

### ISSUE THREAD

**Issue by kurt1288** [lichess-bot-devs/lichess-bot#1053]
From the logs (relevant part included below), it seems like the lichess-bot is reconnecting in the middle of the game (with no information as to why) and upon doing so, sends a command to the engine with an incorrect time of "0". The engine then returns an illegal move causing the game to be resigned.

From the logs:

```
2024-12-10 03:49:21,139 lib.lichess_bot (lichess_bot.py:833) INFO 
2024-12-10 03:49:21,140 lib.lichess_bot (lichess_bot.py:834) INFO move: 60
2024-12-10 03:49:21,141 lib.engine_wrapper (engine_wrapper.py:728) INFO Searching for wtime 28880 btime 26208 for game r5X5QVS3
2024-12-10 03:49:22,230 lib.engine_wrapper (engine_wrapper.py:334) INFO Source: Engine
2024-12-10 03:49:22,231 lib.engine_wrapper (engine_wrapper.py:334) INFO Evaluation: 3.38
2024-12-10 03:49:22,231 lib.engine_wrapper (engine_wrapper.py:334) INFO Depth: 32
2024-12-10 03:49:22,231 lib.engine_wrapper (engine_wrapper.py:334) INFO Nodes: 1.5M
2024-12-10 03:49:22,231 lib.engine_wrapper (engine_wrapper.py:334) INFO Speed: 1.4Knps
2024-12-10 03:49:22,231 lib.engine_wrapper (engine_wrapper.py:334) INFO Pv: 60...Kd3 61. Rf2 Kc4 62. Kg5 Kd4 63. Rc2 Ke3 64. Rb2 Kd3 65. Rf2 Kc3 66. Rf3+ Kb2 67. Rf2+ Kb3 68. Rf3+ Kb4 69. Rf4+ Kc5 70. Rf5+ Kd4 71. Rf2 Kc4 72. Rf4+ Kd5 73. Rf2 Ke6 74. Rd2 Ke5 75. Rc2 Kd6 76. Rf2 Kc7 77. Rc2+ Kb7 78. Rf2 Ka6 79. Rf6+ Ka5 80. Rf5+
2024-12-10 03:49:45,096 lib.lichess_bot (lichess_bot.py:1194) INFO 
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 2024.12.5.2 on Linux 6.11.10-300.fc41.x86_64
    .  //__\
    .  )___(   Play on Lichess with a bot
    
2024-12-10 03:49:45,206 lib.lichess_bot (lichess_bot.py:1197) INFO Checking engine configuration ...
2024-12-10 03:49:46,044 lib.lichess_bot (lichess_bot.py:1200) INFO Engine configuration OK
2024-12-10 03:49:46,764 lib.lichess_bot (lichess_bot.py:1210) INFO Welcome PuffinBot!
2024-12-10 03:49:46,770 lib.lichess_bot (lichess_bot.py:273) INFO You're now connected to https://lichess.org/ and awaiting challenges.
2024-12-10 03:49:47,848 lib.matchmaking (matchmaking.py:293) INFO Next challenge will be created after 03:59:47 (33 challenges in last 24 hours)
2024-12-10 03:49:50,942 lib.lichess_bot (lichess_bot.py:333) INFO --- Process Used. Count: 1. IDs: {'r5X5QVS3'}
2024-12-10 03:49:52,312 lib.lichess_bot (lichess_bot.py:677) INFO +++ https://lichess.org/r5X5QVS3/black Bullet vs BOT InanisBot (2529) (r5X5QVS3)
2024-12-10 03:49:52,323 lib.lichess_bot (lichess_bot.py:833) INFO 
2024-12-10 03:49:52,328 lib.lichess_bot (lichess_bot.py:834) INFO move: 61
2024-12-10 03:49:52,328 lib.engine_wrapper (engine_wrapper.py:728) INFO Searching for wtime 28550 btime 0 for game r5X5QVS3
2024-12-10 03:49:52,745 lib.engine_wrapper (engine_wrapper.py:189) ERROR Ending game due to bot attempting an illegal move.
2024-12-10 03:49:53,236 backoff (_common.py:105) INFO Backing off play_game(...) for 0.3s (chess.engine.EngineError: invalid uci (use 0000 for null moves): 'a8a8')
2024-12-10 03:49:54,588 lib.lichess_bot (lichess_bot.py:677) INFO +++ https://lichess.org/r5X5QVS3/black Bullet vs BOT InanisBot (2529) (r5X5QVS3)
2024-12-10 03:49:54,604 lib.lichess_bot (lichess_bot.py:945) INFO InanisBot won!
2024-12-10 03:49:54,607 lib.lichess_bot (lichess_bot.py:956) INFO PuffinBot resigned.
```

**Comment by AttackingOrDefending** [comment]
Can you upload the debug logs from `/lichess_bot_auto_logs/`?

**Comment by kurt1288** [comment]
[old.log](https://github.com/user-attachments/files/18084054/old.log)

I had two log files in that directory, but this appears to be the only one with that game Id.

**Comment by AttackingOrDefending** [comment]
#1054 will fix this issue by sendinig a minimum time of 1 millisecond to engines (instead of 0 as it does now). The 0ms was correct as your bit had `170` milliseconds left. From that `170` it subtracted `2000` (the `move_overhead` option in `config.yml` which subtracts some time from the base time (`170` in this case) so that the engine doesn't lose on time from the lag).

Unfortunately, I can't understand why the bot crashed from the log. @MarkZH Maybe we should consider storing more log files (e.g. delete them when the folder reaches 100MBs) or use the same file when ichess-bot restarts automatically (but then restarts won't reset everything so it may cause a few bugs in the future).

**Comment by AttackingOrDefending** [comment]
It seems that your engine doesn't support this position and crashes. Here is the output on the console:
```
Puffin 5.0
uci
id name Puffin 5.0
id author Kurt Peters
option name Hash type spin default 32 min 1 max 512
option name Threads type spin default 1 min 1 max 256
uciok
setoption name Hash value 64
isready
readyok
position 8/8/8/8/6Kp/3k4/p4RP1/r7 b - - 19 61
go wtime 28500 btime 27900 winc 1000 binc 1000
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Puffin.Board.GetSquareByPiece(PieceType, Color)
   at Puffin.Search.NegaScout(Int32, Int32, Int32, Int32, Boolean)
   at Puffin.Search.Run()
   at Puffin.ThreadManager.ThreadWork(Int32)
```
I used `Puffin-5.0.exe` for my test.

**Comment by kurt1288** [comment]
> It seems that your engine doesn't support this position and crashes. Here is the output on the console:
> 
> ```
> Puffin 5.0
> uci
> id name Puffin 5.0
> id author Kurt Peters
> option name Hash type spin default 32 min 1 max 512
> option name Threads type spin default 1 min 1 max 256
> uciok
> setoption name Hash value 64
> isready
> readyok
> position 8/8/8/8/6Kp/3k4/p4RP1/r7 b - - 19 61
> go wtime 28500 btime 27900 winc 1000 binc 1000
> Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Puffin.Board.GetSquareByPiece(PieceType, Color)
>    at Puffin.Search.NegaScout(Int32, Int32, Int32, Int32, Boolean)
>    at Puffin.Search.Run()
>    at Puffin.ThreadManager.ThreadWork(Int32)
> ```
> 
> I used `Puffin-5.0.exe` for my test.
> 
> EDIT: Got the same error on linux.

The `position` command is missing the `fen` (i.e. `position fen ...`). I'm able to copy the full position command from the logs (that includes the `position startpos moves ...`) and it searches without crashing.

**Comment by AttackingOrDefending** [comment]
When lichess-bot auto restarts it uses a new file for the logs so that is why the old logs where lost.

I was able to run the engine on that position. When I tested it with 1ms (and with 10ms) I got `a8a8`. Is this the expected behavior of the engine? If so, then it isn't a null move accepted by `python-chess`, even though this doesn't change anything.

lichess-bot auto restarts for 2 reasons:
1. The bot is offline according to lichess
2. There was an error somewhere

It would be weird if lichess considered the bot offline as it played a move about 10 seconds before the restart (if that is the case then maybe we can check a second time if the bot is online after 5 seconds to make sure).

**Comment by kurt1288** [comment]
>Is this the expected behavior of the engine?

Sort of? If the search time is so low that no moves can be obtained then it makes sense to return a null move. But I'm obviously not returning the *technically* correct form of a null move. Though from what you say that shouldn't be a problem here.

The other issue I'm noticing that stems from whatever is going on here is that the engine process ends up being orphaned after all of this (as in it doesn't get killed by lichess-bot).

**Comment by MarkZH** [comment]
@kurt1288 This issue has inspired several changes in lichess-bot. These should either fix the problem or make it easier to debug by keeping logs longer. Please upgrade to the latest version of lichess-bot and let us know if the problem persists.

**Comment by MarkZH** [comment]
Please reopen this issue if the problem persists or if there's new information.
