### ISSUE TITLE
ModuleNotFoundError: No module named 'backoff'

### ISSUE THREAD

**Issue by OhMGod-Dude** [lichess-bot-devs/lichess-bot#652]
I tried to run lichess bot using python 3.11 but I got an error like the below one.

(venv) C:\Users\pererach\Downloads\lichess-bot-master\lichess-bot-master>python3 lichess-bot.py
Traceback (most recent call last):
  File "C:\Users\pererach\Downloads\lichess-bot-master\lichess-bot-master\lichess-bot.py", line 5, in <module>
    import engine_wrapper
  File "C:\Users\pererach\Downloads\lichess-bot-master\lichess-bot-master\engine_wrapper.py", line 16, in <module>
    import lichess
  File "C:\Users\pererach\Downloads\lichess-bot-master\lichess-bot-master\lichess.py", line 6, in <module>
    import backoff
ModuleNotFoundError: No module named 'backoff'

**Comment by AttackingOrDefending** [comment]
Have you run `pip install -r requirements.txt`? You can see [here](https://github.com/lichess-bot-devs/lichess-bot#how-to-install) the exact instructions to install lichess-bot.

**Comment by MarkZH** [comment]
If you still need help with this issue, please reopen.
