### ISSUE TITLE
unclean termination if server returns error

### ISSUE THREAD

**Issue by jdart1** [lichess-bot-devs/lichess-bot#653]
I saw this in the log file - looks like a bug in code that handles server errors:

2023-02-02 06:38:53,770 __main__ ERROR Quitting lichess-bot due to an error:
Traceback (most recent call last):
  File "/home/jdart/chess/lichess-bot/venv/lib/python3.8/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/home/jdart/chess/lichess-bot/lichess.py", line 88, in api_get
    response.raise_for_status()
  File "/home/jdart/chess/lichess-bot/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://lichess.org/api/account

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lichess-bot.py", line 796, in <module>
    start_lichess_bot()
  File "lichess-bot.py", line 745, in start_lichess_bot
    user_profile = li.get_profile()
  File "/home/jdart/chess/lichess-bot/lichess.py", line 226, in get_profile
    profile = self.api_get("profile")
  File "/home/jdart/chess/lichess-bot/venv/lib/python3.8/site-packages/backoff/_sync.py", line 111, in retry
    if giveup(e) or max_tries_exceeded or max_time_exceeded:
TypeError: 'staticmethod' object is not callable

**Comment by AttackingOrDefending** [comment]
Can you test #656?

@MarkZH While fixing this problem, I discovered that if we get rate limited outside `play_game` (e.g. at `profile = self.api_get("profile")`) lichess-bot will quit, because there is no backoff. The chances of this happening are really low, but I think we should probably do something about it.
