### ISSUE TITLE
Lichess-bot.py

### ISSUE THREAD

**Issue by EmptikBest** [lichess-bot-devs/lichess-bot#713]
When I try to execute `python3 lichess-bot.py -u`, I get the following:
`Traceback (most recent call last):
  File "C:\Users\Vinay Kumar\Downloads\lichess-bot-master\lichess-bot-master\lichess-bot.py", line 3, in <module>
    import chess
ModuleNotFoundError: No module named 'chess'`

Also, if I try to run `python3 lichess-bot.py` directly, I get the same issue.

**Comment by AttackingOrDefending** [comment]
Can you try running `python3 -m pip install -r requirements.txt`? And after that run `python3 lichess-bot.py` as normal.

**Comment by EmptikBest** [comment]
Thanks for the reply,
When I try to run`python3 -m pip install -r requirements.txt`, I get the following:
`Collecting chess==1.9.4 (from -r requirements.txt (line 1))
  Using cached chess-1.9.4-py3-none-any.whl (149 kB)
Collecting PyYAML==6.0 (from -r requirements.txt (line 2))
  Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Collecting requests==2.30.0 (from -r requirements.txt (line 3))
  Using cached requests-2.30.0-py3-none-any.whl (62 kB)
Collecting backoff==2.2.1 (from -r requirements.txt (line 4))
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Collecting rich==13.3.5 (from -r requirements.txt (line 5))
  Using cached rich-13.3.5-py3-none-any.whl (238 kB)
Collecting pytest==7.3.1 (from -r requirements.txt (line 8))
  Using cached pytest-7.3.1-py3-none-any.whl (320 kB)
Collecting pytest-timeout==2.1.0 (from -r requirements.txt (line 9))
  Using cached pytest_timeout-2.1.0-py3-none-any.whl (12 kB)
Collecting flake8==6.0.0 (from -r requirements.txt (line 10))
  Using cached flake8-6.0.0-py2.py3-none-any.whl (57 kB)
Collecting flake8-markdown==0.4.0 (from -r requirements.txt (line 11))
  Using cached flake8_markdown-0.4.0-py3-none-any.whl (6.4 kB)
Collecting flake8-docstrings==1.7.0 (from -r requirements.txt (line 12))
  Using cached flake8_docstrings-1.7.0-py2.py3-none-any.whl (5.0 kB)
Collecting mypy==1.2.0 (from -r requirements.txt (line 13))
  Using cached mypy-1.2.0-cp310-cp310-win_amd64.whl (8.9 MB)
Collecting types-requests==2.30.0.0 (from -r requirements.txt (line 14))
  Using cached types_requests-2.30.0.0-py3-none-any.whl (14 kB)
Collecting types-PyYAML==6.0.12.9 (from -r requirements.txt (line 15))
  Using cached types_PyYAML-6.0.12.9-py3-none-any.whl (14 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.30.0->-r requirements.txt (line 3))
  Using cached charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
Collecting idna<4,>=2.5 (from requests==2.30.0->-r requirements.txt (line 3))
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.30.0->-r requirements.txt (line 3))
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17 (from requests==2.30.0->-r requirements.txt (line 3))
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting markdown-it-py<3.0.0,>=2.2.0 (from rich==13.3.5->-r requirements.txt (line 5))
  Using cached markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich==13.3.5->-r requirements.txt (line 5))
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting iniconfig (from pytest==7.3.1->-r requirements.txt (line 8))
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting packaging (from pytest==7.3.1->-r requirements.txt (line 8))
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pluggy<2.0,>=0.12 (from pytest==7.3.1->-r requirements.txt (line 8))
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting exceptiongroup>=1.0.0rc8 (from pytest==7.3.1->-r requirements.txt (line 8))
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting tomli>=1.0.0 (from pytest==7.3.1->-r requirements.txt (line 8))
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting colorama (from pytest==7.3.1->-r requirements.txt (line 8))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting mccabe<0.8.0,>=0.7.0 (from flake8==6.0.0->-r requirements.txt (line 10))
  Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pycodestyle<2.11.0,>=2.10.0 (from flake8==6.0.0->-r requirements.txt (line 10))
  Using cached pycodestyle-2.10.0-py2.py3-none-any.whl (41 kB)
Collecting pyflakes<3.1.0,>=3.0.0 (from flake8==6.0.0->-r requirements.txt (line 10))
  Using cached pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
Collecting pydocstyle>=2.1 (from flake8-docstrings==1.7.0->-r requirements.txt (line 12))
  Using cached pydocstyle-6.3.0-py3-none-any.whl (38 kB)
Collecting typing-extensions>=3.10 (from mypy==1.2.0->-r requirements.txt (line 13))
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting mypy-extensions>=1.0.0 (from mypy==1.2.0->-r requirements.txt (line 13))
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting types-urllib3 (from types-requests==2.30.0.0->-r requirements.txt (line 14))
  Using cached types_urllib3-1.26.25.12-py3-none-any.whl (15 kB)
Collecting mdurl~=0.1 (from markdown-it-py<3.0.0,>=2.2.0->rich==13.3.5->-r requirements.txt (line 5))
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting snowballstemmer>=2.2.0 (from pydocstyle>=2.1->flake8-docstrings==1.7.0->-r requirements.txt (line 12))
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Installing collected packages: types-urllib3, types-PyYAML, snowballstemmer, urllib3, typing-extensions, types-requests, tomli, PyYAML, pygments, pyflakes, pydocstyle, pycodestyle, pluggy, packaging, mypy-extensions, mdurl, mccabe, iniconfig, idna, exceptiongroup, colorama, chess, charset-normalizer, certifi, backoff, requests, pytest, mypy, markdown-it-py, flake8, rich, pytest-timeout, flake8-markdown, flake8-docstrings
Successfully installed PyYAML-6.0 backoff-2.2.1 certifi-2023.5.7 charset-normalizer-3.1.0 chess-1.9.4 colorama-0.4.6 exceptiongroup-1.1.1 flake8-6.0.0 flake8-docstrings-1.7.0 flake8-markdown-0.4.0 idna-3.4 iniconfig-2.0.0 markdown-it-py-2.2.0 mccabe-0.7.0 mdurl-0.1.2 mypy-1.2.0 mypy-extensions-1.0.0 packaging-23.1 pluggy-1.0.0 pycodestyle-2.10.0 pydocstyle-6.3.0 pyflakes-3.0.1 pygments-2.15.1 pytest-7.3.1 pytest-timeout-2.1.0 requests-2.30.0 rich-13.3.5 snowballstemmer-2.2.0 tomli-2.0.1 types-PyYAML-6.0.12.9 types-requests-2.30.0.0 types-urllib3-1.26.25.12 typing-extensions-4.5.0 urllib3-2.0.2`, which I think is fine.

But when I try to run `python3 lichess-bot.py`, I get this:
`[05/08/23 15:13:51] INFO                                                                                                                                                                                                                   lichess-bot.py:933
                                 .   _/|
                                 .  // o\
                                 .  || ._)  lichess-bot 2023.5.6.2
                                 .  //__\
                                 .  )___(   Play on Lichess with a bot

                    ERROR    There appears to be a syntax problem with your config.yml                                                                                                                                                          config.py:290
                             Traceback (most recent call last):
                               File "C:\Users\Vinay Kumar\Downloads\lichess-bot-master\lichess-bot-master\config.py", line 288, in load_config
                                 CONFIG = yaml.safe_load(stream)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 125, in safe_load
                                 return load(stream, SafeLoader)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 81, in load
                                 return loader.get_single_data()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
                                 node = self.get_single_node()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 36, in get_single_node
                                 document = self.compose_document()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 55, in compose_document
                                 node = self.compose_node(None, None)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 64, in compose_node
                                 if self.check_event(AliasEvent):
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\parser.py", line 98, in check_event
                                 self.current_event = self.state()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
                                 if not self.check_token(KeyToken, ValueToken, BlockEndToken):
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 116, in check_token
                                 self.fetch_more_tokens()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
                                 return self.fetch_double()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 655, in fetch_double
                                 self.fetch_flow_scalar(style='"')
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
                                 self.tokens.append(self.scan_flow_scalar(style))
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
                                 chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
                                 raise ScannerError("while scanning a double-quoted scalar", start_mark,
                             yaml.scanner.ScannerError: while scanning a double-quoted scalar
                               in "./config.yml", line 5, column 8
                             expected escape sequence of 8 hexadecimal numbers, but found 's'
                               in "./config.yml", line 5, column 13
                    ERROR    Quitting lichess-bot due to an error:                                                                                                                                                                         lichess-bot.py:994
                             Traceback (most recent call last):
                               File "C:\Users\Vinay Kumar\Downloads\lichess-bot-master\lichess-bot-master\lichess-bot.py", line 991, in <module>
                                 start_lichess_bot()
                               File "C:\Users\Vinay Kumar\Downloads\lichess-bot-master\lichess-bot-master\lichess-bot.py", line 934, in start_lichess_bot
                                 CONFIG = load_config(args.config or "./config.yml")
                               File "C:\Users\Vinay Kumar\Downloads\lichess-bot-master\lichess-bot-master\config.py", line 288, in load_config
                                 CONFIG = yaml.safe_load(stream)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 125, in safe_load
                                 return load(stream, SafeLoader)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 81, in load
                                 return loader.get_single_data()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
                                 node = self.get_single_node()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 36, in get_single_node
                                 document = self.compose_document()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 55, in compose_document
                                 node = self.compose_node(None, None)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 64, in compose_node
                                 if self.check_event(AliasEvent):
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\parser.py", line 98, in check_event
                                 self.current_event = self.state()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
                                 if not self.check_token(KeyToken, ValueToken, BlockEndToken):
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 116, in check_token
                                 self.fetch_more_tokens()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
                                 return self.fetch_double()
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 655, in fetch_double
                                 self.fetch_flow_scalar(style='"')
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
                                 self.tokens.append(self.scan_flow_scalar(style))
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
                                 chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
                               File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
                                 raise ScannerError("while scanning a double-quoted scalar", start_mark,
                             yaml.scanner.ScannerError: while scanning a double-quoted scalar
                               in "./config.yml", line 5, column 8
                             expected escape sequence of 8 hexadecimal numbers, but found 's'
                               in "./config.yml", line 5, column 13`

**Comment by MarkZH** [comment]
If you are using backslashes `\` to write directories (since you are using windows, I'm guessing this is true), you either need to double up the backslashes `\\` or switch to forward slashes `/`. A single backslash will usually cause the next character to be treated in a special way, hence the error message talking about `expected escape sequence of 8 hexadecimal numbers`.

**Comment by AttackingOrDefending** [comment]
Can you send your `config.yml` with the token removed?

**Comment by MarkZH** [comment]
The message for the chat greeting doesn't belong next to `greeting:`. It belongs below it, next to `hello:` or `hello_spectators:`. The `greeting:` line is a section header, so there should be nothing next to it.

**Comment by EmptikBest** [comment]
Thank you, it worked!
