### ISSUE TITLE
TypeError: '>=' not supported between instances of 'datetime.timedelta' and 'int'

### ISSUE THREAD

**Issue by TheYoBots** [lichess-bot-devs/lichess-bot#808]
This is the error:
```
[08/12/23 19:18:08] ERROR    Error while checking challenge
                             WUE9ITRq:                                          
                             Traceback (most recent call last):                 
                               File "/lichess/model.py", line 91, in is_supported                                       
                                 or self.decline_due_to(self.is_supported_recent(config, recent_bot_challenges), "later"))                                          
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               
                               File "/lichess/model.py", line 58, in is_supported_recent                                
                                 recent_bot_challenges[self.challenger.name] = [timer for timer                        
                                                                                ^^^^^^^^^^^^^^^^                        
                               File "/lichess/model.py", line 60, in <listcomp>                                         
                                 if not timer.is_expired()]                     
                                        ^^^^^^^^^^^^^^^^^^                      
                               File "/lichess/timer.py", line 85, in is_expired                                         
                                 return self.time_since_reset() >= self.duration                                      
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       
                             TypeError: '>=' not supported between instances of 'datetime.timedelta' and 'int'
```
I think [this commit](https://github.com/lichess-bot-devs/lichess-bot/commit/ad3390ff0eb7879bbdb86d30d1b31fe39b47cccf) caused this error.

**Comment by MarkZH** [comment]
In line 537 of lichess-bot.py, the `time_window` value needs to be converted to `seconds()`.

**Comment by TheYoBots** [comment]
Thanks! This works!
