### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by EnginnerDog** [lichess-bot-devs/lichess-bot#869]
INFO     Checking engine configuration ...                                                         lichess-bot.py:1026
                    ERROR    Quitting lichess-bot due to an error:                                                     lichess-bot.py:1091
                             Traceback (most recent call last):                                                                           
                               File "/home/runner/lichess-bot/lichess-bot.py", line 1088, in <module>                                     
                                 start_lichess_bot()                                                                                      
                               File "/home/runner/lichess-bot/lichess-bot.py", line 1027, in start_lichess_bot                            
                                 with engine_wrapper.create_engine(CONFIG):                                                               
                               File                                                                                                       
                             "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/contextlib.py                    
                             ", line 135, in __enter__                                                                                    
                                 return next(self.gen)                                                                                    
                               File "/home/runner/lichess-bot/engine_wrapper.py", line 68, in create_engine                               
                                 engine = Engine(commands, options, stderr, cfg.draw_or_resign, cwd=cfg.working_dir)                      
                               File "/home/runner/lichess-bot/engine_wrapper.py", line 457, in __init__                                   
                                 self.engine = chess.engine.SimpleEngine.popen_uci(commands, timeout=10., debug=False,                    
                             setpgrp=False, stderr=stderr,                                                                                
                               File                                                                                                       
                             "/home/runner/lichess-bot/.pythonlibs/lib/python3.10/site-packages/chess/engine.py", line                    
                             3054, in popen_uci                                                                                           
                                 return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp,                    
                             **popen_args)                                                                                                
                               File                                                                                                       
                             "/home/runner/lichess-bot/.pythonlibs/lib/python3.10/site-packages/chess/engine.py", line                    
                             3046, in popen                                                                                               
                                 return run_in_background(background, name=f"{cls.__name__} (command={command!r})",                       
                             debug=debug)                                                                                                 
                               File                                                                                                       
                             "/home/runner/lichess-bot/.pythonlibs/lib/python3.10/site-packages/chess/engine.py", line                    
                             201, in run_in_background                                                                                    
                                 return future.result()                                                                                   
                               File                                                                                                       
                             "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/concurrent/fu                    
                             tures/_base.py", line 458, in result                                                                         
                                 return self.__get_result()                                                                               
                               File                                                                                                       
                             "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/concurrent/fu                    
                             tures/_base.py", line 403, in __get_result                                                                   
                                 raise self._exception                                                                                    
                               File                                                                                                       
                             "/home/runner/lichess-bot/.pythonlibs/lib/python3.10/site-packages/chess/engine.py", line                    
                             195, in background                                                                                           
                                 asyncio.run(coroutine(future))                                                                           
                               File                                                                                                       
                             "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/runne                    
                             rs.py", line 44, in run                                                                                      
                                 return loop.run_until_complete(main)                                                                     
                               File                                                                                                       
                             "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/base_                    
                             events.py", line 649, in run_until_complete                                                                  
                                 return future.result()                                                                                   
                               File                                                                                                       
                             "/home/runner/lichess-bot/.pythonlibs/lib/python3.10/site-packages/chess/engine.py", line                    
                             3038, in background                                                                                          
                                 await asyncio.wait_for(protocol.initialize(), timeout)                                                   
                               File                                                                                                       
                             "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/tasks                    
                             .py", line 445, in wait_for                                                                                  
                                 return fut.result()                                                                                      
                               File                                                                                                       
                             "/home/runner/lichess-bot/.pythonlibs/lib/python3.10/site-packages/chess/engine.py", line                    
                             1510, in initialize                                                                                          
                                 return await self.communicate(UciInitializeCommand)                                                      
                               File                                                                                                       
                             "/home/runner/lichess-bot/.pythonlibs/lib/python3.10/site-packages/chess/engine.py", line                    
                             1133, in communicate                                                                                         
                                 return await command.result                                                                              
                             chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)

**Comment by EnginnerDog** [comment]
i fixed it
