### ISSUE TITLE
Won't play Atomic Game

### ISSUE THREAD

**Issue by timmyFrederiksen** [lichess-bot-devs/lichess-bot#973]
I'm making a bot that I want to only play atomic, and when I hooked up my logic for move finding with only normal chess enabled it runs fine (until it tries to play an illegal move because of differences with atomic), but when I switch the config.yml to only accept atomic, it won't even play the first move, even though the executable is the same in the engines folder. 

When I run "python .\lichess-bot.py", it goes great until I challenge the bot to an atomic game, which is when I receive this error repeatedly:

```
2024-06-08 09:56:27,329 __mp_main__ (lichess-bot.py:780) INFO move: 1
2024-06-08 09:56:27,330 lib.engine_wrapper (engine_wrapper.py:705) INFO Searching for time 10 seconds for game 88n1VosB
2024-06-08 09:56:27,333 backoff (_common.py:105) INFO Backing off play_game(...) for 0.5s (chess.engine.EngineError: engine does not support UCI_Variant)
```

I'm sure, I'm misunderstanding something, the error message seems to imply that it's my engine, but I'm not exactly sure where it is going wrong, here is my engine's code and this exact engine runs on classic chess perfectly (again, until an illegal move is played, but the bot won't even play 1. Nf3 on atomic)

Here is the stack trace on the error in `old.log`:
```
2024-06-08 09:56:27,330 lib.engine_wrapper (engine_wrapper.py:705) INFO Searching for time 10 seconds for game 88n1VosB
2024-06-08 09:56:27,331 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=20156)>: << ucinewgame
2024-06-08 09:56:27,332 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=20156)>: << isready
2024-06-08 09:56:27,333 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=20156)>: >> readyok
2024-06-08 09:56:27,333 backoff (_common.py:105) INFO Backing off play_game(...) for 0.5s (chess.engine.EngineError: engine does not support UCI_Variant)
2024-06-08 09:56:27,333 lib.lichess (lichess.py:65) DEBUG Backing off 0.5 seconds after 1 tries calling function <function play_game at 0x0000029A21789900> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x0000029A1DB45690>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x29a217995a0>, 'user_profile': {'id': 'kaboombot', 'username': 'KaboomBot', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1717728795863, 'seenAt': 1717857526651, 'playTime': {'total': 2519, 'tv': 0}, 'url': 'https://lichess.org/@/KaboomBot', 'count': {'all': 25, 'rated': 0, 'ai': 0, 'draw': 2, 'drawH': 2, 'loss': 6, 'lossH': 6, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x0000029A21799570>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x29a2179a8c0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x29a217da710>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x29a217da9b0>, 'game_id': '88n1VosB'}
2024-06-08 09:56:27,336 chess.engine (engine.py:1059) DEBUG <UciProtocol (pid=20156)>: Process exited
2024-06-08 09:56:27,336 chess.engine (engine.py:1046) DEBUG <UciProtocol (pid=20156)>: Connection lost (exit code: 1, error: None)
2024-06-08 09:56:27,338 lib.lichess (lichess.py:67) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "C:\Users\16126\Desktop\Chess\lichess-bot\lichess-bot.py", line 669, in play_game
    engine.play_move(board,
  File "C:\Users\16126\Desktop\Chess\lichess-bot\lib\engine_wrapper.py", line 181, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
  File "C:\Users\16126\Desktop\Chess\lichess-bot\lib\engine_wrapper.py", line 257, in search
    result = self.engine.play(board,
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2982, in play
    return future.result()
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1789, in play
    return await self.communicate(UciPlayCommand)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1133, in communicate
    return await command.result
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1386, in _line_received
    self.line_received(engine, line)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1728, in line_received
    self._readyok(engine)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1734, in _readyok
    engine._position(board)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1607, in _position
    raise EngineError("engine does not support UCI_Variant")
chess.engine.EngineError: engine does not support UCI_Variant
```

and in `new.log`:
```
2024-06-08 10:16:54,530 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/bot/game/stream/ZEk7uYYh HTTP/1.1" 200 None
2024-06-08 10:16:54,531 __mp_main__ (lichess-bot.py:614) DEBUG Initial state: {'id': 'ZEk7uYYh', 'variant': {'key': 'atomic', 'name': 'Atomic', 'short': 'Atom'}, 'speed': 'rapid', 'perf': {'name': 'Atomic'}, 'rated': False, 'createdAt': 1717859810971, 'white': {'id': 'kaboombot', 'name': 'KaboomBot', 'title': 'BOT', 'rating': 1500, 'provisional': True}, 'black': {'id': 'tfrederiksen', 'name': 'tFrederiksen', 'title': None, 'rating': 1555}, 'initialFen': 'startpos', 'clock': {'initial': 600000, 'increment': 0}, 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': '', 'wtime': 600000, 'btime': 600000, 'winc': 0, 'binc': 0, 'status': 'started'}}
2024-06-08 10:16:54,531 lib.engine_wrapper (engine_wrapper.py:65) DEBUG Starting engine: ['C:\\Users\\16126\\Desktop\\Chess\\lichess-bot\\engines\\bot.exe']
2024-06-08 10:16:54,533 asyncio (proactor_events.py:626) DEBUG Using proactor: IocpProactor
2024-06-08 10:16:54,554 chess.engine (engine.py:1040) DEBUG <UciProtocol (pid=25480)>: Connection made
2024-06-08 10:16:54,554 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=25480)>: << uci
2024-06-08 10:16:54,730 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=25480)>: >> Chess Random Mover
2024-06-08 10:16:54,730 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=25480)>: >> uciok
2024-06-08 10:16:54,731 __mp_main__ (lichess-bot.py:620) DEBUG The engine for game ZEk7uYYh has pid=25480
2024-06-08 10:16:54,731 __mp_main__ (lichess-bot.py:623) INFO +++ https://lichess.org/ZEk7uYYh/white Atomic vs tFrederiksen (1555) (ZEk7uYYh)
2024-06-08 10:16:54,731 __mp_main__ (lichess-bot.py:788) DEBUG Game state: {'type': 'gameState', 'moves': '', 'wtime': 600000, 'btime': 600000, 'winc': 0, 'binc': 0, 'status': 'started'}
2024-06-08 10:16:54,731 lib.conversation (conversation.py:102) INFO *** https://lichess.org/ZEk7uYYh/white [player] KaboomBot: Hi! I'm KaboomBot. Good luck!
2024-06-08 10:16:54,732 urllib3.connectionpool (connectionpool.py:1055) DEBUG Starting new HTTPS connection (3): lichess.org:443
2024-06-08 10:16:55,097 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/ZEk7uYYh/chat HTTP/1.1" 200 11
2024-06-08 10:16:55,097 lib.conversation (conversation.py:102) INFO *** https://lichess.org/ZEk7uYYh/white [spectator] KaboomBot: Hi! I'm KaboomBot.
2024-06-08 10:16:55,222 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/ZEk7uYYh/chat HTTP/1.1" 200 11
2024-06-08 10:16:55,223 __mp_main__ (lichess-bot.py:779) INFO 
2024-06-08 10:16:55,224 __mp_main__ (lichess-bot.py:780) INFO move: 1
2024-06-08 10:16:55,224 lib.engine_wrapper (engine_wrapper.py:705) INFO Searching for time 10 seconds for game ZEk7uYYh
2024-06-08 10:16:55,225 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=25480)>: << ucinewgame
2024-06-08 10:16:55,225 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=25480)>: << isready
2024-06-08 10:16:55,226 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=25480)>: >> readyok
2024-06-08 10:16:55,227 backoff (_common.py:105) INFO Backing off play_game(...) for 1.6s (chess.engine.EngineError: engine does not support UCI_Variant)
2024-06-08 10:16:55,227 lib.lichess (lichess.py:65) DEBUG Backing off 1.6 seconds after 2 tries calling function <function play_game at 0x0000025F2D979900> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x0000025F29DC5690>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x25f2d9895a0>, 'user_profile': {'id': 'kaboombot', 'username': 'KaboomBot', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1717728795863, 'seenAt': 1717858577974, 'playTime': {'total': 2519, 'tv': 0}, 'url': 'https://lichess.org/@/KaboomBot', 'count': {'all': 25, 'rated': 0, 'ai': 0, 'draw': 2, 'drawH': 2, 'loss': 6, 'lossH': 6, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x0000025F2D989570>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x25f2d98a8c0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x25f2d9ca710>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x25f2d9ca9b0>, 'game_id': 'ZEk7uYYh'}
2024-06-08 10:16:55,229 lib.lichess (lichess.py:67) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "C:\Users\16126\Desktop\Chess\lichess-bot\lichess-bot.py", line 669, in play_game
    engine.play_move(board,
  File "C:\Users\16126\Desktop\Chess\lichess-bot\lib\engine_wrapper.py", line 181, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
  File "C:\Users\16126\Desktop\Chess\lichess-bot\lib\engine_wrapper.py", line 257, in search
    result = self.engine.play(board,
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2982, in play
    return future.result()
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1789, in play
    return await self.communicate(UciPlayCommand)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1133, in communicate
    return await command.result
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1386, in _line_received
    self.line_received(engine, line)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1728, in line_received
    self._readyok(engine)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1734, in _readyok
    engine._position(board)
  File "C:\Users\16126\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1607, in _position
    raise EngineError("engine does not support UCI_Variant")
chess.engine.EngineError: engine does not support UCI_Variant
```

 - OS: Windows
 - Python Version: 3.10.6
 - Terminal: using the VS Code terminal

If there's anything else needed, please let me know. I'm pretty sure this is not a bug, but I can't find anything in documentation or online that would explain the issue.

Thanks

**Comment by timmyFrederiksen** [comment]
I'm attaching the code to my engine and the config.yml as well

config.yml
***

token: "lip_vxP3HbSCa9cf0QgbFRAO"    # Lichess OAuth2 Token.
url: "https://lichess.org/"        # Lichess base URL.

engine:                            # Engine settings.
  dir: "./engines/"                # Directory containing the engine. This can be an absolute path or one relative to lichess-bot/.
  name: "bot.exe"              # Binary name of the engine to use.
  working_dir: ""                  # Directory where the chess engine will read and write files. If blank or missing, the current directory is used.
                                   # NOTE: If working_dir is set, the engine will look for files and directories relative to this directory, not where lichess-bot was launched. Absolute paths are unaffected.
  protocol: "uci"                  # "uci", "xboard" or "homemade"
  ponder: true                     # Think on opponent's time.

  polyglot:
    enabled: false                 # Activate polyglot book.
    book:
      # standard:                    # List of book file paths for variant standard.
      #   - engines/book1.bin
      #   - engines/book2.bin
    atomic:                      # List of book file paths for variant atomic.
      - engines/atomicbook1.bin
      - engines/atomicbook2.bin
#     etc.
#     Use the same pattern for 'chess960', 'giveaway' (antichess), 'crazyhouse', 'horde', 'kingofthehill', 'racingkings' and '3check' as well.
    min_weight: 1                  # Does not select moves with weight below min_weight (min 0, max: 65535).
    selection: "weighted_random"   # Move selection is one of "weighted_random", "uniform_random" or "best_move" (but not below the min_weight in the 2nd and 3rd case).
    max_depth: 20                  # How many moves from the start to take from the book.

  draw_or_resign:
    resign_enabled: false          # Whether or not the bot should resign.
    resign_score: -1000            # If the score is less than or equal to this value, the bot resigns (in cp).
    resign_for_egtb_minus_two: true # If true the bot will resign in positions where the online_egtb returns a wdl of -2.
    resign_moves: 3                # How many moves in a row the score has to be below the resign value.
    offer_draw_enabled: true       # Whether or not the bot should offer/accept draw.
    offer_draw_score: 0            # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp).
    offer_draw_for_egtb_zero: true # If true the bot will offer/accept draw in positions where the online_egtb returns a wdl of 0.
    offer_draw_moves: 10           # How many moves in a row the absolute value of the score has to be below the draw value.
    offer_draw_pieces: 10          # Only if the pieces on board are less than or equal to this value, the bot offers/accepts draw.

  online_moves:
    max_out_of_book_moves: 10      # Stop using online opening books after they don't have a move for 'max_out_of_book_moves' positions. Doesn't apply to the online endgame tablebases.
    max_retries: 2                 # The maximum amount of retries when getting an online move.
    # max_depth: 10                # How many moves from the start to take from online books. Default is no limit.
    chessdb_book:
      enabled: false               # Whether or not to use chessdb book.
      min_time: 20                 # Minimum time (in seconds) to use chessdb book.
      move_quality: "good"         # One of "all", "good", "best".
      min_depth: 20                # Only for move_quality: "best".
    lichess_cloud_analysis:
      enabled: false               # Whether or not to use lichess cloud analysis.
      min_time: 20                 # Minimum time (in seconds) the bot must have to use cloud analysis.
      move_quality: "best"         # One of "good", "best".
      max_score_difference: 50     # Only for move_quality: "good". The maximum score difference (in cp) between the best move and the other moves.
      min_depth: 20
      min_knodes: 0
    lichess_opening_explorer:
      enabled: false
      min_time: 20
      source: "masters"            # One of "lichess", "masters", "player"
      player_name: ""              # The lichess username. Leave empty for the bot's username to be used. Used only when source is "player".
      sort: "winrate"              # One of "winrate", "games_played"
      min_games: 10                # Minimum number of times a move must have been played to be chosen.
    online_egtb:
      enabled: false               # Whether or not to enable online endgame tablebases.
      min_time: 20                 # Minimum time (in seconds) the bot must have to use online EGTBs.
      max_pieces: 7                # Maximum number of pieces on the board to use endgame tablebases.
      source: "lichess"            # One of "lichess", "chessdb".
      move_quality: "best"         # One of "best" or "suggest" (it takes all the moves with the same WDL and tells the engine to only consider these; will move instantly if there is only 1 "good" move).

  lichess_bot_tbs:                 # The tablebases list here will be read by lichess-bot, not the engine.
    syzygy:
      enabled: false               # Whether or not to use local syzygy endgame tablebases.
      paths:                       # Paths to Syzygy endgame tablebases.
        - "engines/syzygy"
      max_pieces: 7                # Maximum number of pieces in the endgame tablebase.
      move_quality: "best"         # One of "best" or "suggest" (it takes all the moves with the same WDL and tells the engine to only consider these; will move instantly if there is only 1 "good" move).
    gaviota:
      enabled: false               # Whether or not to use local gaviota endgame tablebases.
      paths:
        - "engines/gaviota"
      max_pieces: 5
      min_dtm_to_consider_as_wdl_1: 120 # The minimum DTM to consider as syzygy WDL=1/-1. Set to 100 to disable.
      move_quality: "best"         # One of "best" or "suggest" (it takes all the moves with the same WDL and tells the engine to only consider these; will move instantly if there is only 1 "good" move).

# engine_options:                  # Any custom command line params to pass to the engine.
#   cpuct: 3.1

  homemade_options:
#   Hash: 256

  uci_options:                     # Arbitrary UCI options passed to the engine.
  #   Move Overhead: 100             # Increase if your bot flags games too often.
  #   Threads: 4                     # Max CPU threads the engine can use.
  #   Hash: 512                      # Max memory (in megabytes) the engine can allocate.
  #   SyzygyPath: "./syzygy/"        # Paths to Syzygy endgame tablebases that the engine reads.
  #   UCI_ShowWDL: true              # Show the chance of the engine winning.
  # go_commands:                   # Additional options to pass to the UCI go command.
  #   nodes: 1                     # Search so many nodes only.
  #   depth: 5                     # Search depth ply only.
  #   movetime: 1000               # Integer. Search exactly movetime milliseconds.

# xboard_options:                  # Arbitrary XBoard options passed to the engine.
#   cores: "4"
#   memory: "4096"
#   egtpath:                       # Directory containing egtb (endgame tablabases), relative to this project. For 'xboard' engines.
#     gaviota: "Gaviota path"
#     nalimov: "Nalimov Path"
#     scorpio: "Scorpio Path"
#     syzygy: "Syzygy Path"
#   go_commands:                   # Additional options to pass to the XBoard go command.
#     depth: 5                     # Search depth ply only.
#     Do note that the go commands 'movetime' and 'nodes' are invalid and may cause bad time management for XBoard engines.

  # silence_stderr: false            # Some engines (yes you, Leela) are very noisy.

abort_time: 30                     # Time to abort a game in seconds when there is no activity.
fake_think_time: false             # Artificially slow down the bot to pretend like it's thinking.
rate_limiting_delay: 0             # Time (in ms) to delay after sending a move to prevent "Too Many Requests" errors.
move_overhead: 2000                # Increase if your bot flags games too often.
max_takebacks_accepted: 0          # The number of times to allow an opponent to take back a move in a game.
quit_after_all_games_finish: false # If set to true, then pressing Ctrl-C to quit will only stop lichess-bot after all current games have finished.

correspondence:
  move_time: 60                    # Time in seconds to search in correspondence games.
  checkin_period: 300              # How often to check for opponent moves in correspondence games after disconnecting.
  disconnect_time: 150             # Time before disconnecting from a correspondence game.
  ponder: false                    # Ponder in correspondence games the bot is connected to.

challenge:                         # Incoming challenges.
  concurrency: 1                   # Number of games to play simultaneously.
  sort_by: "best"                  # Possible values: "best" and "first".
  accept_bot: true                 # Accepts challenges coming from other bots.
  only_bot: false                  # Accept challenges by bots only.
  max_increment: 20                # Maximum amount of increment to accept a challenge in seconds. The max is 180. Set to 0 for no increment.
  min_increment: 0                 # Minimum amount of increment to accept a challenge in seconds.
  max_base: 1800                   # Maximum amount of base time to accept a challenge in seconds. The max is 10800 (3 hours).
  min_base: 0                      # Minimum amount of base time to accept a challenge in seconds.
  max_days: 14                     # Maximum number of days per move to accept a challenge for a correspondence game.
                                   # Unlimited games can be accepted by removing this field or specifying .inf
  min_days: 1                      # Minimum number of days per move to accept a challenge for a correspondence game.
  variants:                        # Chess variants to accept (https://lichess.org/variant).
    # - standard
#   - fromPosition
#   - antichess
    - atomic
#   - chess960
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:                   # Time controls to accept (bots are not allowed to play ultraBullet).
    - bullet
    - blitz
    - rapid
    - classical
#   - correspondence
  modes:                           # Game modes to accept.
    - casual                       # Unrated games.
    - rated                        # Rated games - must comment if the engine doesn't try to win.
# block_list:                      # List of users from which the challenges are always declined.
#   - user1
#   - user2
# allow_list:                      # List of users from which challenges are exclusively accepted, all others being declined. If empty, challenges from all users may be accepted.
#   - user3
#   - user4
# recent_bot_challenge_age: 60     # Maximum age of a bot challenge to be considered recent in seconds
# max_recent_bot_challenges: 2     # Maximum number of recent challenges that can be accepted from the same bot
  bullet_requires_increment: False # Require that bullet game challenges from bots have a non-zero increment

greeting:
  # Optional substitution keywords (include curly braces):
  #   {opponent} to insert opponent's name
  #   {me} to insert bot's name
  # Any other words in curly braces will be removed.
  hello: "Hi! I'm {me}. Good luck!" # Message to send to opponent chat at the start of a game
  goodbye: "Good game!" # Message to send to opponent chat at the end of a game
  hello_spectators: "Hi! I'm {me}." # Message to send to spectator chat at the start of a game
  goodbye_spectators: "Thanks for watching!" # Message to send to spectator chat at the end of a game

# pgn_directory: "game_records"    # A directory where PGN-format records of the bot's games are kept
# pgn_file_grouping: "game"        # How to group games into files. Options are "game", "opponent", and "all"
                                   # "game" (default) - every game is written to a different file named "{White name} vs. {Black name} - {lichess game ID}.pgn"
                                   # "opponent" - every game with a given opponent is written to a file named "{Bot name} games vs. {Opponent name}.pgn"
                                   # "all" - every game is written to a single file named "{Bot name} games.pgn"

matchmaking:
  allow_matchmaking: false         # Set it to 'true' to challenge other bots.
  allow_during_games: false        # Set it to 'true' to create challenges during long games.
  challenge_variant: "random"      # If set to 'random', the bot will choose one variant from the variants enabled in 'challenge.variants'.
  challenge_timeout: 30            # Create a challenge after being idle for 'challenge_timeout' minutes. The minimum is 1 minute.
  challenge_initial_time:          # Initial time in seconds of the challenge (to be chosen at random).
    - 60
    - 180
  challenge_increment:             # Increment in seconds of the challenge (to be chosen at random).
    - 1
    - 2
#  challenge_days:                 # Days for correspondence challenge (to be chosen at random).
#    - 1
#    - 2
# opponent_min_rating: 600         # Opponents rating should be above this value (600 is the minimum rating in lichess).
# opponent_max_rating: 4000        # Opponents rating should be below this value (4000 is the maximum rating in lichess).
  opponent_rating_difference: 300  # The maximum difference in rating between the bot's rating and opponent's rating.
  rating_preference: "none"        # One of "none", "high", "low".
  opponent_allow_tos_violation: false # Set to 'true' to allow challenging bots that violated the Lichess Terms of Service.
  challenge_mode: "random"         # Set it to the mode in which challenges are sent. Possible options are 'casual', 'rated' and 'random'.
  challenge_filter: none           # If a bot declines a challenge, do not issue a similar challenge to that bot. Possible options are 'none', 'coarse', and 'fine'.
# block_list:                      # The list of bots that will not be challenged
#   - user1
#   - user2

# overrides:                       # List of overrides for the matchmaking specifications above. When a challenge is created, either the default specification above or one of the overrides will be randomly chosen.
#   bullet_only_horde:             # Name of the override. Can be anything as long as each override has a unique name ("bullet_only_horde" and "easy_chess960" in these examples).
#     challenge_variant: "horde"   # List of options to override. Only the options mentioned will change when making the challenge. The rest will follow the default matchmaking options above.
#     challenge_initial_time:
#       - 1
#       - 2
#     challenge_increment:
#       - 0
#       - 1
#
#   easy_chess960:
#     challenge_variant: "chess960"
#     opponent_min_rating: 400
#     opponent_max_rating: 1200
#     opponent_rating_difference:
#     challenge_mode: casual
#
#   no_pressure_correspondence:
#     challenge_initial_time:
#     challenge_increment:
#     challenge_days:
#       - 2
#       - 3
#     challenge_mode: casual
#
# The following configurations cannot be overridden: allow_matchmaking, challenge_timeout, challenge_filter and block_list.

***


And the engine

***

import chess
import random
import sys
import chess.variant

# UCI commands
UCI_COMMAND = 'uci'
UCI_OK_COMMAND = 'uciok'
IS_READY_COMMAND = 'isready'
READY_OK_COMMAND = 'readyok'
POSITION_COMMAND = 'position' 
MOVES_COMMAND = 'moves'
GO_COMMAND = 'go'
QUIT_COMMAND = 'quit'
BEST_MOVE_COMMAND = 'bestmove'

def write_uci_ok():
    output(UCI_OK_COMMAND)

def write_ready_ok():
    output(READY_OK_COMMAND)

def get_move_list(s):
    move_list = ''
    pos = s.find(MOVES_COMMAND)
    if pos >= 0:
        move_list = s[(pos+len(MOVES_COMMAND)):]
    return move_list

def extract_substring(a: str, b: str) -> str:
    if a.startswith(b):
        start_index = len(b)
        end_index = a.find(' ', start_index)
        if end_index == -1:  # No space found, take the rest of the string
            end_index = len(a)
        return a[start_index:end_index]
    else:
        return ""

def output_move(move_list):
    board = chess.variant.AtomicBoard()
    moves = move_list.split(' ')
    str = ""
    for m in moves:
        if m != '':
            str += board.san(chess.Move.from_uci(m)) + ' '
            board.push_uci(m)
    print(str)
    
    # If playing as black
    if board.ply() % 2 == 1:
        best_move = random.choice(list(board.legal_moves))
        output(BEST_MOVE_COMMAND + ' ' + best_move.uci())
    
    # If White, and turn 1
    if board.ply() == 0:
        best_move = chess.Move.from_uci("g1f3")

    else:
        best_move = random.choice(list(board.legal_moves))
        for line in lines:
            str2 = extract_substring(line, str)
            if str2 != "":
                print(str2)
                best_move = board.parse_san(str2)
                break
        
        #Check for checks & mates
            
    output(BEST_MOVE_COMMAND + ' ' + best_move.uci())

def log(s, prefix = '>>> '):
    if log_mode:
        f = open("log.txt", "a")
        f.write(prefix + s + '\n')
        f.close()

def output(s):
    print(s)
    log(s, '')
    
def read_in_white_storage():
    try:
        with open("white_storage.txt", 'r') as file:
            lines = file.readlines()
            lines = [line.rstrip('\n') for line in lines]
            return lines
    except FileNotFoundError:
        print(f"Error: File not found.")
        return []

def main(argv):
    global log_mode
    global lines
    log_mode = False
    
    lines = read_in_white_storage()

    print('Chess Random Mover')

    for arg in argv:
        if arg == '--log':
            log_mode = True
        if arg in ('-h', '--help', '-?', '/?'):
            print('Usage: chess-random-mover [--log]')
            print('Use --log parameter to log UCI data')
    
    move_list = ''
    while True:
        s = input()
        log(s)
        commands = s.split(' ')
        if len(commands) == 0:
            continue
            
        if commands[0] == UCI_COMMAND:
            write_uci_ok()
        elif commands[0] == IS_READY_COMMAND:
            write_ready_ok()
        elif commands[0] == POSITION_COMMAND:
            move_list = get_move_list(s)
        elif commands[0] == GO_COMMAND:
            output_move(move_list)
        elif commands[0] == QUIT_COMMAND:
            break
        

if __name__ == '__main__':
    main(sys.argv[1:])

***

**Comment by timmyFrederiksen** [comment]
I'm attaching text files with the code for both my config.yml (config.txt) and my engine (bot.txt) [coded in python]
[bot.txt](https://github.com/user-attachments/files/15748628/bot.txt)
[config.txt](https://github.com/user-attachments/files/15748629/config.txt)

**Comment by AttackingOrDefending** [comment]
In `bot.txt` can you try changing `UCI_OK_COMMAND = 'uciok'` to `UCI_OK_COMMAND = 'option name UCI_Variant type combo default atomic var atomic\nuciok'`?

**Comment by timmyFrederiksen** [comment]
Yes, that worked! Why did that work, haha?

**Comment by MarkZH** [comment]
In order to play chess variants, your bot needs to announce that it can play those variants. Otherwise, chess interfaces (like lichess-bot) will assume the bot only plays standard chess. That's the purpose of the `option name UCI_Variant` command. If your bot ever plays more variants, add more `var` parameters to the same line.

**Comment by timmyFrederiksen** [comment]
Appreciate the help!
